"""empty message

Revision ID: 149c8624df9d
Revises: 435a9cb66378
Create Date: 2015-10-22 19:17:51.158930

"""

# revision identifiers, used by Alembic.
revision = '149c8624df9d'
down_revision = '435a9cb66378'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_event', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_event')
    ### end Alembic commands ###
