"""empty message

Revision ID: 1bf2e5a8cbfd
Revises: 595e8d3025f9
Create Date: 2015-10-19 21:17:22.307200

"""

# revision identifiers, used by Alembic.
revision = '1bf2e5a8cbfd'
down_revision = '595e8d3025f9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('promptevent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptevent',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('prompt_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'events.id'], name=u'promptevent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('promptevents')
    ### end Alembic commands ###
