"""empty message

Revision ID: 1f14f1a8e044
Revises: 22a52b3f1a47
Create Date: 2015-10-19 21:41:25.325576

"""

# revision identifiers, used by Alembic.
revision = '1f14f1a8e044'
down_revision = '22a52b3f1a47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    ### end Alembic commands ###
