"""empty message

Revision ID: 22a52b3f1a47
Revises: 1bf2e5a8cbfd
Create Date: 2015-10-19 21:17:48.031234

"""

# revision identifiers, used by Alembic.
revision = '22a52b3f1a47'
down_revision = '1bf2e5a8cbfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
