"""empty message

Revision ID: 235ae148f7a8
Revises: 1f14f1a8e044
Create Date: 2015-10-19 21:42:12.093184

"""

# revision identifiers, used by Alembic.
revision = '235ae148f7a8'
down_revision = '1f14f1a8e044'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
