"""empty message

Revision ID: 24ce9b11fec0
Revises: 54dc5ea142ae
Create Date: 2015-10-19 21:13:53.659799

"""

# revision identifiers, used by Alembic.
revision = '24ce9b11fec0'
down_revision = '54dc5ea142ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
