"""empty message

Revision ID: 27c4bc6ae23f
Revises: 542e5ba5600e
Create Date: 2015-10-19 20:45:42.447885

"""

# revision identifiers, used by Alembic.
revision = '27c4bc6ae23f'
down_revision = '542e5ba5600e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
