"""empty message

Revision ID: 2e31f018f2c0
Revises: 9340ace70a0
Create Date: 2015-10-22 19:36:30.757750

"""

# revision identifiers, used by Alembic.
revision = '2e31f018f2c0'
down_revision = '9340ace70a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
