"""empty message

Revision ID: 349a7da29b4
Revises: 149c8624df9d
Create Date: 2015-10-22 19:17:54.567453

"""

# revision identifiers, used by Alembic.
revision = '349a7da29b4'
down_revision = '149c8624df9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
