"""empty message

Revision ID: 38156b146f96
Revises: 4c77e49b9df0
Create Date: 2015-10-19 20:52:49.017456

"""

# revision identifiers, used by Alembic.
revision = '38156b146f96'
down_revision = '4c77e49b9df0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
