"""empty message

Revision ID: 3995402a6451
Revises: 4986da6506d9
Create Date: 2015-10-19 20:16:24.464730

"""

# revision identifiers, used by Alembic.
revision = '3995402a6451'
down_revision = '4986da6506d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
