"""empty message

Revision ID: 4069e5c60e17
Revises: 51f5ccfba190
Create Date: 2015-10-19 19:59:50.750428

"""

# revision identifiers, used by Alembic.
revision = '4069e5c60e17'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
