"""empty message

Revision ID: 435a9cb66378
Revises: 45bdc70991d5
Create Date: 2015-10-22 14:00:14.739152

"""

# revision identifiers, used by Alembic.
revision = '435a9cb66378'
down_revision = '45bdc70991d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
