"""empty message

Revision ID: 45bdc70991d5
Revises: 235ae148f7a8
Create Date: 2015-10-22 14:00:07.564480

"""

# revision identifiers, used by Alembic.
revision = '45bdc70991d5'
down_revision = '235ae148f7a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('current', sa.Boolean(), nullable=True))
    op.alter_column('events', 'location',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'location',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.drop_column('events', 'current')
    ### end Alembic commands ###
