"""empty message

Revision ID: 4986da6506d9
Revises: 4069e5c60e17
Create Date: 2015-10-19 20:14:57.020409

"""

# revision identifiers, used by Alembic.
revision = '4986da6506d9'
down_revision = '4069e5c60e17'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
