"""empty message

Revision ID: 4a3370a77752
Revises: 5abd44b3f21e
Create Date: 2015-10-22 19:34:01.020555

"""

# revision identifiers, used by Alembic.
revision = '4a3370a77752'
down_revision = '5abd44b3f21e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
