"""empty message

Revision ID: 4c77e49b9df0
Revises: 27c4bc6ae23f
Create Date: 2015-10-19 20:52:16.785706

"""

# revision identifiers, used by Alembic.
revision = '4c77e49b9df0'
down_revision = '27c4bc6ae23f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventprompts', 'user_id')
    op.create_index('ix_eventprompts_event_id', 'eventprompts', ['event_id'], unique=False)
    op.create_unique_constraint(None, 'eventprompts', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventprompts')
    op.drop_index('ix_eventprompts_event_id', 'eventprompts')
    op.add_column('eventprompts', sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
