"""empty message

Revision ID: 50231725caef
Revises: 38156b146f96
Create Date: 2015-10-19 20:52:51.714132

"""

# revision identifiers, used by Alembic.
revision = '50231725caef'
down_revision = '38156b146f96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
