"""empty message

Revision ID: 542e5ba5600e
Revises: 3995402a6451
Create Date: 2015-10-19 20:45:38.465925

"""

# revision identifiers, used by Alembic.
revision = '542e5ba5600e'
down_revision = '3995402a6451'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_date', 'events', ['date'], unique=False)
    op.create_index('ix_events_timestamp', 'events', ['timestamp'], unique=False)
    op.create_table('eventprompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'posts', sa.Column('event_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'posts', 'event_id')
    op.drop_table('eventprompts')
    op.drop_index('ix_events_timestamp', 'events')
    op.drop_index('ix_events_date', 'events')
    op.drop_table('events')
    op.drop_table('prompts')
    ### end Alembic commands ###
