"""empty message

Revision ID: 54dc5ea142ae
Revises: 50231725caef
Create Date: 2015-10-19 21:11:48.969886

"""

# revision identifiers, used by Alembic.
revision = '54dc5ea142ae'
down_revision = '50231725caef'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promptevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    # sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eventprompts')
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'user_id')
    op.create_table('eventprompts',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('prompt_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'events.id'], name=u'eventid'),
    sa.ForeignKeyConstraint(['prompt_id'], [u'prompts.id'], name=u'promptid'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('promptevent')
    ### end Alembic commands ###
