"""empty message

Revision ID: 595e8d3025f9
Revises: df7ecbda800
Create Date: 2015-10-19 21:15:30.037688

"""

# revision identifiers, used by Alembic.
revision = '595e8d3025f9'
down_revision = 'df7ecbda800'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
