"""empty message

Revision ID: 5abd44b3f21e
Revises: 349a7da29b4
Create Date: 2015-10-22 19:33:58.466361

"""

# revision identifiers, used by Alembic.
revision = '5abd44b3f21e'
down_revision = '349a7da29b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('browser', sa.String(length=64), nullable=True))
    op.add_column('events', sa.Column('platform', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'platform')
    op.drop_column('events', 'browser')
    ### end Alembic commands ###
