"""empty message

Revision ID: 9340ace70a0
Revises: 4a3370a77752
Create Date: 2015-10-22 19:36:26.302856

"""

# revision identifiers, used by Alembic.
revision = '9340ace70a0'
down_revision = '4a3370a77752'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'platform')
    op.drop_column('events', 'browser')
    op.add_column('posts', sa.Column('browser', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('platform', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'platform')
    op.drop_column('posts', 'browser')
    op.add_column('events', sa.Column('browser', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('events', sa.Column('platform', mysql.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
