"""empty message

Revision ID: df7ecbda800
Revises: 24ce9b11fec0
Create Date: 2015-10-19 21:14:08.796778

"""

# revision identifiers, used by Alembic.
revision = 'df7ecbda800'
down_revision = '24ce9b11fec0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
